CREATE TABLE IF NOT EXISTS USERS
(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255),
    ROLE VARCHAR(55),
    PROVIDER VARCHAR(45),
    PROVIDER_ID VARCHAR(45)
    );
